# Generated by Django 5.2.3 on 2025-09-29 06:39

import django.core.validators
import django.db.models.deletion
import medicalstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0002_contact_us_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('category_image', models.ImageField(upload_to='Categories_images/')),
                ('category_image_altername', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500, unique=True)),
                ('product_main_image', models.ImageField(upload_to=medicalstore.models.product_image_upload_path)),
                ('product_image2', models.ImageField(blank=True, null=True, upload_to=medicalstore.models.product_image_upload_path)),
                ('product_image3', models.ImageField(blank=True, null=True, upload_to=medicalstore.models.product_image_upload_path)),
                ('product_image4', models.ImageField(blank=True, null=True, upload_to=medicalstore.models.product_image_upload_path)),
                ('product_image5', models.ImageField(blank=True, null=True, upload_to=medicalstore.models.product_image_upload_path)),
                ('product_image_altername', models.CharField(blank=True, max_length=40, null=True)),
                ('product_desc', models.CharField(max_length=1500)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.IntegerField(blank=True, help_text='Enter discount between 1 and 100', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('featured_option', models.CharField(blank=True, choices=[('sale', 'Sale'), ('new', 'New'), ('bestseller', 'Bestseller')], max_length=10, null=True)),
                ('rating', models.IntegerField(blank=True, help_text='Leave empty when adding products. It will auto-calculate.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='medicalstore.category')),
            ],
        ),
    ]
