# Generated by Django 5.2.3 on 2025-09-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_background_color',
            field=models.CharField(blank=True, choices=[('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('light red', 'Light red'), ('violet', 'Violet')], max_length=30, null=True),
        ),
    ]
