# Generated by Django 5.2.3 on 2025-09-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0004_category_category_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_background_color',
            field=models.CharField(choices=[('pink', 'Pink'), ('blue', 'Blue'), ('green', 'Green'), ('orange', 'Orange'), ('light red', 'Light red'), ('violet', 'Violet')], max_length=30),
        ),
    ]
