# Generated by Django 5.2.3 on 2025-09-29 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0005_alter_category_category_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_option',
            field=models.CharField(blank=True, choices=[('Sale', 'Sale'), ('New', 'New'), ('Bestseller', 'Bestseller')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0, help_text='Leave empty when adding products. It will auto-calculate.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
