# Generated by Django 5.2.3 on 2025-09-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0006_alter_product_featured_option_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_short_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
