# Generated by Django 5.2.3 on 2025-09-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0007_product_product_short_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(default='0', help_text='If no stock while adding enter value as 0.'),
            preserve_default=False,
        ),
    ]
