# Generated by Django 5.2.3 on 2025-09-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0008_product_available_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image_altername',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_short_desc',
            field=models.CharField(max_length=150),
        ),
    ]
