# Generated by Django 5.2.3 on 2025-09-29 19:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0010_alter_product_discount_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Limit_Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_limit_count', models.PositiveIntegerField(default=10, help_text='Enter discount between 10 and 50', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
            ],
        ),
    ]
