# Generated by Django 5.2.3 on 2025-09-29 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0011_products_limit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products_limit_value',
            name='product_limit_count',
            field=models.PositiveIntegerField(default=10, help_text='Enter discount between 10 and 50', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
