# Generated by Django 5.2.3 on 2025-09-29 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0013_alter_product_featured_option_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart_Item',
        ),
        migrations.RenameModel(
            old_name='WishlistCart',
            new_name='Wishlist_Cart',
        ),
        migrations.RenameModel(
            old_name='WishlistCartItem',
            new_name='Wishlist_Cart_Item',
        ),
    ]
