# Generated by Django 5.2.3 on 2025-09-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0014_rename_cartitem_cart_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image5',
            new_name='product_image1',
        ),
    ]
