# Generated by Django 5.2.3 on 2025-10-02 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0016_order_orderitem_payment_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
            preserve_default=False,
        ),
    ]
