# Generated by Django 5.2.3 on 2025-10-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0017_shippingaddress_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_cart_item',
            name='wishlistcart',
        ),
        migrations.RemoveField(
            model_name='wishlist_cart_item',
            name='product',
        ),
        migrations.DeleteModel(
            name='Wishlist_Cart',
        ),
        migrations.DeleteModel(
            name='Wishlist_Cart_Item',
        ),
    ]
