# Generated by Django 5.2.3 on 2025-10-02 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0019_wishlist_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist_cart_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalstore.product'),
        ),
    ]
