# Generated by Django 5.2.3 on 2025-10-02 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0020_alter_wishlist_cart_item_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist_Cart_Item',
        ),
    ]
