# Generated by Django 5.2.3 on 2025-10-02 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0022_wishlist_cart_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist_Cart_Item',
        ),
    ]
