# Generated by Django 5.2.3 on 2025-10-02 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0023_delete_wishlist_cart_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistcartitem', to='medicalstore.product')),
                ('wishlistcart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistcartitem', to='medicalstore.wishlist_cart')),
            ],
        ),
    ]
