# Generated by Django 5.2.3 on 2025-10-02 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0024_wishlist_cart_wishlistcartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishlistCartItem',
            new_name='Wishlist_Cart_Item',
        ),
    ]
