# Generated by Django 5.2.3 on 2025-10-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0025_rename_wishlistcartitem_wishlist_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
