# Generated by Django 5.2.3 on 2025-10-02 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0027_user_detail_state_alter_shippingaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='pincode',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100001), django.core.validators.MaxValueValidator(999999)]),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='pincode',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100001), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
