# Generated by Django 5.2.3 on 2025-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0029_alter_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cancelled_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_payment_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='out_for_delivery_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_raw_response',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='refund_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='shipped_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount_refunded',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refund_status',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('not confirmed', 'Not confirmed'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('out for delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='not confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('not paid', 'Not Paid'), ('paid', 'Paid'), ('failed', 'Failed')], default='not paid', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='created', max_length=10),
        ),
    ]
