# Generated by Django 5.2.3 on 2025-10-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0030_remove_orderitem_cancelled_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products_Limit_Value',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
