# Generated by Django 5.2.3 on 2025-10-07 00:23

import medicalstore.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalstore', '0032_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=medicalstore.models.user_image_upload_path),
        ),
    ]
